### ISSUE TITLE
advice on how to run with volumes for data and code

### ISSUE THREAD

**Issue by laurencefass** [Ismaestro/angular6-example-app#22]
### Bug Report or Feature Request (mark with an `x`)

- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ x ] support request!
 
### Versions.

question: how do i get versions for these from command line. dont see to be on universal paths....

### The log given by the failure.

n/a

### Desired functionality.

i would like to run the app and access both code and superhero data from my docker host. please can you identify file structure for the app so i can set up correct volumes.

**Comment by Ismaestro** [comment]
Check [this section](https://angular.io/tutorial/toh-pt6#simulate-a-data-server) of the official documentation, in order to modify the code to simulate a web server (and not use my API) and have the possibility to have both things in the same docker image.
The docker commands would be:
```
npm run docker
docker ps
docker exec -it [CONTAINER ID] sh
```

Once inside the container, the folder with the website files is under:
```
ls /usr/share/nginx/html
```

BR
